server:
  port: 8010
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/auth_service
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/auth_service
    user: root
    password: root


# Logging level configuration
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb.core: DEBUG

# Actuator endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
